window.TheDaySeedData = {
  "source": "品項叫貨.xlsx",
  "importedAt": "2026-05-31",
  "stores": [
    {
      "id": "store-太一",
      "name": "太一",
      "manager": "公司",
      "phone": "",
      "address": "",
      "status": "啟用",
      "staff": [
        "公司",
        "瑪莉",
        "una",
        "喬安娜",
        "啊蕊",
        "cindy"
      ]
    },
    {
      "id": "store-烏日",
      "name": "烏日",
      "manager": "公司",
      "phone": "",
      "address": "",
      "status": "啟用",
      "staff": [
        "公司",
        "水",
        "玉米",
        "KATE",
        "紫琦",
        "哈迪",
        "比薩"
      ]
    },
    {
      "id": "store-甲一",
      "name": "甲一",
      "manager": "公司",
      "phone": "",
      "address": "",
      "status": "啟用",
      "staff": [
        "公司",
        "lisa",
        "emma",
        "ice",
        "ian",
        "anna",
        "baki",
        "fanny",
        "俊"
      ]
    },
    {
      "id": "store-甲二",
      "name": "甲二",
      "manager": "公司",
      "phone": "",
      "address": "",
      "status": "啟用",
      "staff": [
        "公司",
        "AVA",
        "MIKA",
        "LARA",
        "IRIS",
        "beka"
      ]
    },
    {
      "id": "store-苑裡",
      "name": "苑裡",
      "manager": "公司",
      "phone": "",
      "address": "",
      "status": "啟用",
      "staff": [
        "公司",
        "LINA",
        "kelly"
      ]
    }
  ],
  "products": [
    {
      "id": "product-001-伊黛莉-蛋白雙氧水3%",
      "brand": "伊黛莉",
      "category": "藥水",
      "name": "蛋白雙氧水3%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-002-伊黛莉-蛋白雙氧水6%",
      "brand": "伊黛莉",
      "category": "藥水",
      "name": "蛋白雙氧水6%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-003-伊黛莉-蛋白雙氧水9%",
      "brand": "伊黛莉",
      "category": "藥水",
      "name": "蛋白雙氧水9%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-004-伊黛莉-蛋白雙氧水12%",
      "brand": "伊黛莉",
      "category": "藥水",
      "name": "蛋白雙氧水12%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-005-伊黛莉-去色劑",
      "brand": "伊黛莉",
      "category": "藥水",
      "name": "去色劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-006-伊黛莉-植萃精油",
      "brand": "伊黛莉",
      "category": "護髮",
      "name": "植萃精油",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-007-伊黛莉染膏-10cv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "10CV",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-008-伊黛莉染膏-10l",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "10L",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-009-伊黛莉染膏-10pc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "10PC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-010-伊黛莉染膏-10pd",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "10PD",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-011-伊黛莉染膏-11ac",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "11AC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-012-伊黛莉染膏-11ap",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "11AP",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-013-伊黛莉染膏-1c",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "1C",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-014-伊黛莉染膏-2n",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "2N",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-015-伊黛莉染膏-3ch",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "3CH",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-016-伊黛莉染膏-3n",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "3N",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-017-伊黛莉染膏-4ch",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4CH",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-018-伊黛莉染膏-4cl",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4CL",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-019-伊黛莉染膏-4nf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4NF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-020-伊黛莉染膏-5c",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5C",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-021-伊黛莉染膏-5ch",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5CH",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-022-伊黛莉染膏-5cl",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5CL",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-023-伊黛莉染膏-5ii",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5II",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-024-伊黛莉染膏-5m",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5M",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-025-伊黛莉染膏-5n",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5N",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-026-伊黛莉染膏-5nf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5NF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-027-伊黛莉染膏-5ni",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5Ni",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-028-伊黛莉染膏-5rf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5RF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-029-伊黛莉染膏-5v",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5V",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-030-伊黛莉染膏-6b",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6B",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-031-伊黛莉染膏-6c",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6C",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-032-伊黛莉染膏-6ca",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6CA",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-033-伊黛莉染膏-6cc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6CC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-034-伊黛莉染膏-6n",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6N",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-035-伊黛莉染膏-6ni",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6ni",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-036-伊黛莉染膏-6r",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6R",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-037-伊黛莉染膏-6rf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6RF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-038-伊黛莉染膏-6t",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6T",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-039-伊黛莉染膏-6uv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6uv",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-040-伊黛莉染膏-7b",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7B",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-041-伊黛莉染膏-7c",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7C",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-042-伊黛莉染膏-7cc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7CC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-043-伊黛莉染膏-7cl",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7CL",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-044-伊黛莉染膏-7cv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7CV",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-045-伊黛莉染膏-7ii",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7II",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-046-伊黛莉染膏-7l",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7L",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-047-伊黛莉染膏-7nf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7NF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-048-伊黛莉染膏-7pc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7pc",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-049-伊黛莉染膏-7rf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7RF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-050-伊黛莉染膏-7rv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7RV",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-051-伊黛莉染膏-8b",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8b",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-052-伊黛莉染膏-8cc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8CC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-053-伊黛莉染膏-8cv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8cv",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-054-伊黛莉染膏-8l",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8L",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-055-伊黛莉染膏-8nf",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8NF",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-056-伊黛莉染膏-8pc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8PC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-057-伊黛莉染膏-8r",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8R",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-058-伊黛莉染膏-9b",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9B",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-059-伊黛莉染膏-9cc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9CC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-060-伊黛莉染膏-9cv",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9cv",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-061-伊黛莉染膏-9ii",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9II",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-062-伊黛莉染膏-9l",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9L",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-063-伊黛莉染膏-9pc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9PC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-064-伊黛莉染膏-9po",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9PO",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-065-伊黛莉染膏-ab",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "AB",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-066-伊黛莉染膏-av",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "AV",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-067-伊黛莉染膏-n",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "N",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-068-伊黛莉染膏-ssc",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "SSC",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-069-伊黛莉染膏-ssm",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "SSM",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-070-伊黛莉染膏-7ru",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7RU",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-071-伊黛莉染膏-ssn",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "SSN",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-072-伊黛莉染膏-5rl",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5RL",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-073-伊黛莉染膏-wr",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "WR",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-074-伊黛莉染膏-ar",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "AR",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-075-伊黛莉染膏-6d",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6D",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-076-伊黛莉染膏-7d",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7D",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-077-伊黛莉染膏-8d",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8D",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-078-伊黛莉染膏-9d",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9D",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-079-伊黛莉染膏-4r",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4R",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-080-伊黛莉染膏-4v",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4V",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-081-伊黛莉染膏-4m",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "4M",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-082-伊黛莉染膏-7a",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7A",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-083-伊黛莉染膏-6k",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6K",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-084-伊黛莉染膏-7k",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "7K",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-085-伊黛莉染膏-8k",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "8K",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-086-伊黛莉染膏-9k",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "9K",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-087-伊黛莉染膏-1v",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "1V",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-088-伊黛莉染膏-5ca",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "5CA",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-089-伊黛莉染膏-6ru",
      "brand": "伊黛莉染膏",
      "category": "染膏",
      "name": "6RU",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-090-水恩沛染膏-2-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "2/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-091-水恩沛染膏-3-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "3/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-092-水恩沛染膏-4-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "4/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-093-水恩沛染膏-5-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-094-水恩沛染膏-6-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-095-水恩沛染膏-7-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-096-水恩沛染膏-8-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-097-水恩沛染膏-9-0",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-098-水恩沛染膏-4-1",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "4/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-099-水恩沛染膏-6-1",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-100-水恩沛染膏-8-1",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-101-水恩沛染膏-11-1",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-102-水恩沛染膏-6-2",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-103-水恩沛染膏-8-2",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-104-水恩沛染膏-6-17",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/17",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-105-水恩沛染膏-8-17",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/17",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-106-水恩沛染膏-5-37",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5/37",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-107-水恩沛染膏-6-37",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/37",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-108-水恩沛染膏-7-37",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/37",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-109-水恩沛染膏-8-37",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/37",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-110-水恩沛染膏-5-77",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5/77",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-111-水恩沛染膏-6-77",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/77",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-112-水恩沛染膏-7-77",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/77",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-113-水恩沛染膏-6-43",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/43",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-114-水恩沛染膏-8-43",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/43",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-115-水恩沛染膏-5-45",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5/45",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-116-水恩沛染膏-7-45",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/45",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-117-水恩沛染膏-褪色膏",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "褪色膏",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-118-水恩沛染膏-透明色",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "透明色",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-119-水恩沛染膏-4rb",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "4rb",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-120-水恩沛染膏-4w",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "4w",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-121-水恩沛染膏-5n",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5n",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-122-水恩沛染膏-5m",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5m",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-123-水恩沛染膏-5w",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5w",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-124-水恩沛染膏-5c",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5c",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-125-水恩沛染膏-5rb",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "5rb",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-126-水恩沛染膏-7rb",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7rb",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-127-水恩沛染膏-7m",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7m",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-128-水恩沛染膏-7w",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7w",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-129-水恩沛染膏-7-11",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/11",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-130-水恩沛染膏-9-11",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/11",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-131-水恩沛染膏-11-11",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/11",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-132-水恩沛染膏-7-16",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/16",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-133-水恩沛染膏-8-16",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/16",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-134-水恩沛染膏-9-16",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/16",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-135-水恩沛染膏-11-16",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/16",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-136-水恩沛染膏-7-20",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/20",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-137-水恩沛染膏-9-20",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/20",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-138-水恩沛染膏-11-20",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/20",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-139-水恩沛染膏-7-81",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/81",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-140-水恩沛染膏-8-81",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/81",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-141-水恩沛染膏-9-81",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/81",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-142-水恩沛染膏-11-81",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/81",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-143-水恩沛染膏-7-41",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-144-水恩沛染膏-8-41",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "8/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-145-水恩沛染膏-9-41",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-146-水恩沛染膏-11-41",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-147-水恩沛染膏-7-65",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "7/65",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-148-水恩沛染膏-6-66",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "6/66",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-149-水恩沛染膏-9-65",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "9/65",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-150-水恩沛染膏-11-65",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "11/65",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-151-水恩沛染膏-藍綠色0-28",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "藍綠色0/28",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-152-水恩沛染膏-加強黃0-33",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "加強黃0/33",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-153-水恩沛染膏-加強紅0-55",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "加強紅0/55",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-154-水恩沛染膏-加強紫0-66",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "加強紫0/66",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-155-水恩沛染膏-冰藍100-88",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "冰藍100/88",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-156-水恩沛染膏-灰0-11",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "灰0/11",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-157-水恩沛染膏-綠0-22",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "綠0/22",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-158-水恩沛染膏-藍0-88",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "藍0/88",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-159-水恩沛染膏-橙0-44",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "橙0/44",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-160-水恩沛染膏-紫0-65",
      "brand": "水恩沛染膏",
      "category": "染膏",
      "name": "紫0/65",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-161-水恩沛-3%",
      "brand": "水恩沛",
      "category": "一般品項",
      "name": "3%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-162-水恩沛-6%",
      "brand": "水恩沛",
      "category": "一般品項",
      "name": "6%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-163-水恩沛-9%",
      "brand": "水恩沛",
      "category": "一般品項",
      "name": "9%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-164-水恩沛-12%",
      "brand": "水恩沛",
      "category": "一般品項",
      "name": "12%",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-165-寶齡-頭皮修護精華液1號",
      "brand": "寶齡",
      "category": "護髮",
      "name": "頭皮修護精華液1號",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-166-寶齡-黑密再生2號",
      "brand": "寶齡",
      "category": "一般品項",
      "name": "黑密再生2號",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-167-寶齡-頭皮舒張凝露",
      "brand": "寶齡",
      "category": "頭皮",
      "name": "頭皮舒張凝露",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-168-寶齡-角質淨化凝露",
      "brand": "寶齡",
      "category": "一般品項",
      "name": "角質淨化凝露",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-169-寶齡-深層虹吸泥膜250g",
      "brand": "寶齡",
      "category": "護髮",
      "name": "深層虹吸泥膜250g",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-170-寶齡-昇髮密碼養髮液3號",
      "brand": "寶齡",
      "category": "頭皮",
      "name": "昇髮密碼養髮液3號",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-171-寶齡-舒姸洗髮精",
      "brand": "寶齡",
      "category": "洗髮",
      "name": "舒姸洗髮精",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-172-阿蘇卡-水光感-髮浴800ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光感-髮浴800ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-173-阿蘇卡-水光感-重建霜800ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光感-重建霜800ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-174-阿蘇卡-水光感髮妝水800ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光感髮妝水800ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-175-阿蘇卡-水光感髮妝水-小",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光感髮妝水(小)",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-176-阿蘇卡-ha健康一劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "HA健康一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-177-阿蘇卡-da一劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "DA一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-178-阿蘇卡-sa1劑一般受損",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "SA1劑一般受損",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-179-阿蘇卡-ca1劑嚴重受損",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "CA1劑嚴重受損",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-180-阿蘇卡-膏狀2劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "膏狀2劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-181-阿蘇卡-健康水狀2劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "健康水狀2劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-182-阿蘇卡-pe髮浴780ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "PE髮浴780ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-183-阿蘇卡-hkp-150ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "HKP 150ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-184-阿蘇卡-pp-150ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "PP 150ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-185-阿蘇卡-hkp-780ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "HKP  780ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-186-阿蘇卡-pp-780ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "PP  780ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-187-阿蘇卡-hk嚴重縮毛髮質1劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "HK嚴重縮毛髮質1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-188-阿蘇卡-cck混和型髮質1劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "CCK混和型髮質1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-189-阿蘇卡-pc慕絲狀150ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "Pc慕絲狀150ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-190-阿蘇卡-pc慕絲狀780ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "PC慕絲狀780ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-191-阿蘇卡-bc精華油50ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "BC精華油50ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-192-阿蘇卡-bc精華油300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "BC精華油300ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-193-阿蘇卡-hc1健康冷燙1劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "HC1健康冷燙1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-194-阿蘇卡-sc1健康冷燙1劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "SC1健康冷燙1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-195-阿蘇卡-cc1嚴重受損1劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "CC1嚴重受損1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-196-阿蘇卡-dc受損冷燙一劑",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "DC受損冷燙一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-197-阿蘇卡-水光組a--bc.pc",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光組A （bc.pc)",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-198-阿蘇卡-水光組b--水凍蜜-精華油",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "水光組B (水凍蜜 精華油）",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-199-阿蘇卡-活力菁露100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "活力菁露100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-200-阿蘇卡-活力髮浴300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "活力髮浴300ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-201-阿蘇卡-活力髮浴1000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "活力髮浴1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-202-阿蘇卡-活力噴霧100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "活力噴霧100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-203-阿蘇卡-油屑菁露100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "油屑菁露100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-204-阿蘇卡-油屑髮浴300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "油屑髮浴300ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-205-阿蘇卡-油屑髮浴1000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "油屑髮浴1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-206-阿蘇卡-油屑噴霧100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "油屑噴霧100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-207-阿蘇卡-乾屑菁露100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "乾屑菁露100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-208-阿蘇卡-乾屑髮浴300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "乾屑髮浴300ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-209-阿蘇卡-乾屑髮浴1000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "乾屑髮浴1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-210-阿蘇卡-乾屑噴霧100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "乾屑噴霧100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-211-阿蘇卡-控油菁露100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "控油菁露100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-212-阿蘇卡-控油髮浴300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "控油髮浴300ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-213-阿蘇卡-控油髮浴1000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "控油髮浴1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-214-阿蘇卡-控油噴霧100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "控油噴霧100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-215-阿蘇卡-舒敏菁露100ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "舒敏菁露100ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-216-阿蘇卡-舒敏髮浴300ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "舒敏髮浴300ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-217-阿蘇卡-舒敏髮浴1000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "舒敏髮浴1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-218-阿蘇卡-舒敏噴霧100m",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "舒敏噴霧100M",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-219-阿蘇卡-pe髮浴4000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "PE髮浴4000ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-220-阿蘇卡-極潤重建霜2000ml",
      "brand": "阿蘇卡",
      "category": "一般品項",
      "name": "極潤重建霜2000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-221-阿蘇卡-極潤洗髮精",
      "brand": "阿蘇卡",
      "category": "洗髮",
      "name": "極潤洗髮精",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-222-蘊洛-tg健康1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "TG健康1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-223-蘊洛-tg受損1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "TG受損1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-224-蘊洛-tg抗拒1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "TG抗拒1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-225-蘊洛-tg抗拒--1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "TG抗拒+ 1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-226-蘊洛-ca受損1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "CA受損1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-227-蘊洛-ca極受損1劑500ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "CA極受損1劑500ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-228-蘊洛-雙氧水狀2劑1000ml",
      "brand": "蘊洛",
      "category": "藥水",
      "name": "雙氧水狀2劑1000ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-229-蘊洛-溴酸鈉水狀2劑1000ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "溴酸鈉水狀2劑1000ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-230-蘊洛-雙氧膏狀2劑1000ml",
      "brand": "蘊洛",
      "category": "藥水",
      "name": "雙氧膏狀2劑1000ml",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-231-蘊洛-鉑金",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "鉑金",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-232-蘊洛-激活",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "激活",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-233-蘊洛-濃密",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "濃密",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-234-蘊洛-鎖色洗髮精2000ml",
      "brand": "蘊洛",
      "category": "洗髮",
      "name": "鎖色洗髮精2000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-235-蘊洛-晶亮噴霧",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "晶亮噴霧",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-236-蘊洛-絲曜封膜一劑",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "絲曜封膜一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-237-蘊洛-絲曜封膜二劑",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "絲曜封膜二劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-238-蘊洛-絲曜封膜三劑",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "絲曜封膜三劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-239-蘊洛-絲曜封膜四劑",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "絲曜封膜四劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-240-蘊洛-絲曜封膜4-劑",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "絲曜封膜4+劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-241-蘊洛-抗熱護髮素",
      "brand": "蘊洛",
      "category": "護髮",
      "name": "抗熱護髮素",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-242-蘊洛-金馬禮盒",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "金馬禮盒",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-243-蘊洛-水生乳",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "水生乳",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-244-蘊洛-水生油",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "水生油",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-245-蘊洛-鎖色洗髮精700ml",
      "brand": "蘊洛",
      "category": "洗髮",
      "name": "鎖色洗髮精700ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-246-蘊洛-汗濕洗髮精500ml",
      "brand": "蘊洛",
      "category": "洗髮",
      "name": "汗濕洗髮精500ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-247-蘊洛-汗濕洗髮精2000ml",
      "brand": "蘊洛",
      "category": "洗髮",
      "name": "汗濕洗髮精2000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-248-蘊洛-濃密120ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "濃密120ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-249-蘊洛-激活120ml",
      "brand": "蘊洛",
      "category": "一般品項",
      "name": "激活120ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-250-聖馥-sl雙氧6",
      "brand": "聖馥",
      "category": "藥水",
      "name": "SL雙氧6％",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-251-聖馥-sl雙氧9",
      "brand": "聖馥",
      "category": "藥水",
      "name": "SL雙氧9％",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-252-聖馥-sl雙氧12",
      "brand": "聖馥",
      "category": "藥水",
      "name": "SL雙氧12％",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-253-聖馥-漂粉",
      "brand": "聖馥",
      "category": "藥水",
      "name": "漂粉",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-254-聖馥染膏150ml-灰",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "灰",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-255-聖馥染膏150ml-紅",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "紅",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-256-聖馥染膏150ml-紫",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "紫",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-257-聖馥染膏150ml-橘",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "橘",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-258-聖馥染膏150ml-綠",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "綠",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-259-聖馥染膏150ml-藍紫",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "藍紫",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-260-聖馥染膏150ml-藍",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "藍",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-261-聖馥染膏150ml-n3-0",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N3/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-262-聖馥染膏150ml-n4-0",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-263-聖馥染膏150ml-n5-0",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N5/0",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-264-聖馥染膏150ml-n4-2",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-265-聖馥染膏150ml-n4-3",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/3",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-266-聖馥染膏150ml-n4-4",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/4",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-267-聖馥染膏150ml-n4-5",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/5",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-268-聖馥染膏150ml-n4-6",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/6",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-269-聖馥染膏150ml-n4-7",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/7",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-270-聖馥染膏150ml-n4-8",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "N4/8",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-271-聖馥染膏150ml-6683",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "6683",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-272-聖馥染膏150ml-lite藍",
      "brand": "聖馥染膏150ML",
      "category": "染膏",
      "name": "lite藍",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-273-聖馥染膏100ml-77-1",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "77/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-274-聖馥染膏100ml-55-41",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "55/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-275-聖馥染膏100ml-55-61",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "55/61",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-276-聖馥染膏100ml-77-2",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "77/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-277-聖馥染膏100ml-88-41",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "88/41",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-278-聖馥染膏100ml-88-4",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "88/4",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-279-聖馥染膏100ml-77-34",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "77/34",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-280-聖馥染膏100ml-77-80",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "77/80",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-281-聖馥染膏100ml-55-87",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "55/87",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-282-聖馥染膏100ml-66-87",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "66/87",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-283-聖馥染膏100ml-88-62",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "88/62",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-284-聖馥染膏100ml-88-87",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "88/87",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-285-聖馥染膏100ml-9928",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "9928",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-286-聖馥染膏100ml-8883",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8883",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-287-聖馥染膏100ml-661",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "661",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-288-聖馥染膏100ml-6-66",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "6/66",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-289-聖馥染膏100ml-12-00",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "12/00",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-290-聖馥染膏100ml-12-01",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "12/01",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-291-聖馥染膏100ml-12-02",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "12/02",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-292-聖馥染膏100ml-6-1",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "6/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-293-聖馥染膏100ml-8-1",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-294-聖馥染膏100ml-2-17",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "2/17",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-295-聖馥染膏100ml-1-11",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "1/11",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-296-聖馥染膏100ml-4-2",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "4/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-297-聖馥染膏100ml-7-2",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "7/2",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-298-聖馥染膏100ml-6-34",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "6/34",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-299-聖馥染膏100ml-8-34",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8/34",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-300-聖馥染膏100ml-5-4",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "5/4",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-301-聖馥染膏100ml-7-4",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "7/4",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-302-聖馥染膏100ml-6-46",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "6/46",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-303-聖馥染膏100ml-8-46",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8/46",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-304-聖馥染膏100ml-6-5",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "6/5",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-305-聖馥染膏100ml-8-5",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8/5",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-306-聖馥染膏100ml-5-6",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "5/6",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-307-聖馥染膏100ml-7-6",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "7/6",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-308-聖馥染膏100ml-5-7",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "5/7",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-309-聖馥染膏100ml-7-7",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "7/7",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-310-聖馥染膏100ml-8-7",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "8/7",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-311-聖馥染膏100ml-10-1",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "10/1",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-312-聖馥染膏100ml-05-04",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "05/04",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-313-聖馥染膏100ml-05-07",
      "brand": "聖馥染膏100ML",
      "category": "染膏",
      "name": "05/07",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-314-哥德式-哥德式tg冷燙一劑",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式TG冷燙一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-315-哥德式-哥德式tg冷燙二劑",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式TG冷燙二劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-316-哥德式-哥德式-m1-受損液狀",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式(M1)受損液狀",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-317-哥德式-哥德式-m3-受損乳狀",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式(M3)受損乳狀",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-318-哥德式-哥德式-m4-受損乳狀",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式(M4)受損乳狀",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-319-哥德式-aqsh1水鑽光溫塑1劑",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "AQSH1水鑽光溫塑1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-320-哥德式-aq.h1.水鑚光溫塑1劑",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "AQ.H1.水鑚光溫塑1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-321-哥德式-aq.n1.水鑽光溫塑1劑",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "AQ.N1.水鑽光溫塑1劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-322-哥德式-哥德式nl2水",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式NL2水",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-323-哥德式-哥德式n2膏",
      "brand": "哥德式",
      "category": "一般品項",
      "name": "哥德式N2膏",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-324-威傑士-酷冷",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "酷冷",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-325-威傑士-冷霧灰",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "冷霧灰",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-326-威傑士-灰紫",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "灰紫",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-327-威傑士-粉灰紫",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "粉灰紫",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-328-威傑士-潮綠",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "潮綠",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-329-威傑士-甜橘",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "甜橘",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-330-威傑士-豔紅",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "豔紅",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-331-威傑士-摩卡棕",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "摩卡棕",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-332-威傑士-奶霜",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "奶霜",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-333-威傑士-炫紫",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "炫紫",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-334-威傑士-矯色",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "矯色",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-335-威傑士-海洋藍",
      "brand": "威傑士",
      "category": "一般品項",
      "name": "海洋藍",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-336-首席-高濃度外泌體",
      "brand": "首席",
      "category": "一般品項",
      "name": "高濃度外泌體",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-337-首席-居家外泌體",
      "brand": "首席",
      "category": "一般品項",
      "name": "居家外泌體",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-338-首席-臉部外泌體",
      "brand": "首席",
      "category": "一般品項",
      "name": "臉部外泌體",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-339-首席-親膚洗髮精-涼",
      "brand": "首席",
      "category": "洗髮",
      "name": "親膚洗髮精（涼）",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-340-首席-親膚洗髮精-不涼",
      "brand": "首席",
      "category": "洗髮",
      "name": "親膚洗髮精（不涼）",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-341-首席-低敏頭皮隔離",
      "brand": "首席",
      "category": "頭皮",
      "name": "低敏頭皮隔離",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-342-其餘品項-魔梗一劑",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "魔梗一劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-343-其餘品項-魔梗二劑",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "魔梗二劑",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-344-其餘品項-油頭蠟",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "油頭蠟",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-345-其餘品項-旅行組",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "旅行組",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-346-其餘品項-水漾洗髮精",
      "brand": "其餘品項",
      "category": "洗髮",
      "name": "水漾洗髮精",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-347-其餘品項-t1極致修護",
      "brand": "其餘品項",
      "category": "護髮",
      "name": "T1極致修護",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-348-其餘品項-雙向精華液",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "雙向精華液",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-349-其餘品項-pf頭皮深層潔髮露",
      "brand": "其餘品項",
      "category": "頭皮",
      "name": "pf頭皮深層潔髮露",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-350-其餘品項-輕量泡沫烘捲",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "輕量泡沫烘捲",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-351-其餘品項-t3-30ml",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "T3(30ML)",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-352-其餘品項-t1-30ml",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "T1(30ml)",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-353-其餘品項-t2奈姸",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "T2奈姸",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-354-其餘品項-提袋",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "提袋",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-355-其餘品項-鉑金",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "鉑金",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-356-其餘品項-深層大桶洗髮精",
      "brand": "其餘品項",
      "category": "洗髮",
      "name": "深層大桶洗髮精",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-357-其餘品項-香氛修護平衡素",
      "brand": "其餘品項",
      "category": "護髮",
      "name": "香氛修護平衡素",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-358-其餘品項-s1舒姸植萃1000ml",
      "brand": "其餘品項",
      "category": "一般品項",
      "name": "s1舒姸植萃1000ML",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    },
    {
      "id": "product-359-其餘品項-無味洗髮精",
      "brand": "其餘品項",
      "category": "洗髮",
      "name": "無味洗髮精",
      "spec": "",
      "unit": "個",
      "price": 0,
      "active": true,
      "note": "價格待補"
    }
  ]
};
